camera:
  iso: 0
  last-pic-number: 0
  zoom: 0
general-info:
  description: description
  name: name
  output-formats:
  - pdfbeads
scantailor:
  color-mode: black_and_white
  despeckle: off
  dewarping: auto
  dpi-x: 300
  dpi-y: 300
  l: 1.5
  margins-bottom: 2.5
  margins-left: 2.5
  margins-right: 2.5
  margins-top: 2.5
  threshold: 0
tesseract:
  input-extension: tif
  lang: spa
  output-format: hocr